_BASE_: "./Base-RCNN-C4.yaml"
OUTPUT_DIR: "output/test_bdd"
INPUT:
  CROP:
    ENABLED: True
  MIN_SIZE_TRAIN: (550,)
MODEL:
  PIXEL_STD: [57.375, 57.120, 58.395]
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN_shortcut"
  BACKBONE:
    NAME: "build_vgg_backbone"
  MASK_ON: False
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    IN_FEATURES: ["vgg4"]
    PRE_NMS_TOPK_TRAIN: 12000
    POST_NMS_TOPK_TRAIN: 2000
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "CrossEntropy"
    NUM_CLASSES: 8
    IN_FEATURES: ["vgg4"]
    BATCH_SIZE_PER_IMAGE: 512
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  WEIGHTS: "weights/vgg16_bn-6c64b313_converted.pth"
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (60000, 80000, 90000, 360000)
  # STEPS: (30000, 35000, 90000, 360000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 60000
  IMG_PER_BATCH_LABEL: 4
  IMG_PER_BATCH_UNLABEL: 4
  BASE_LR: 0.04
  CHECKPOINT_PERIOD: 5000
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("cityscapes_fine_instance_seg_train",)
  TRAIN_UNLABEL: ("ACDC_val_night",)
  TEST: ("cityscapes_val","ACDC_val_night")
SEMISUPNET:
  Trainer: "dinoteacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 20
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "vgg4"
  DIS_LOSS_WEIGHT: 0.0
  USE_FEATURE_ALIGN: False
  FEATURE_ALIGN_LAYER: "vgg4"
  ALIGN_MODEL: "dinov2_vitb14" 
  ALIGN_HEAD_TYPE: "MLP"  # attention, MLP, MLP3, linear
  ALIGN_HEAD_PROJ_DIM: 1024
  ALIGN_PROJ_GELU: False
  ALIGN_HEAD_NORMALIZE: True
  ALIGN_EASY_ONLY: True
  FEATURE_ALIGN_TARGET_START: 10
  FEATURE_ALIGN_LOSS_WEIGHT: 1.0
  FEATURE_ALIGN_LOSS_WEIGHT_TARGET: 1.0 
  LABELER_TARGET_PSEUDOGT: None
  LABELER_PSEUDOGT_SWAP: False
  LABELER_PSEUDOGT_SWAP_ITER: 100000
  DINO_PATCH_SIZE: 14
TEST:
  EVAL_PERIOD: 50



