_BASE_: "./Base-RCNN-C4.yaml"
OUTPUT_DIR: "output/test_vgg_city2fgcity_pseudo_labels_LangSAM"
INPUT:
  CROP:
    ENABLED: True
  MIN_SIZE_TRAIN: (550,)
MODEL:
  # META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  # RPN:
  #   POSITIVE_FRACTION: 0.25
  ROI_HEADS:
    NAME: "StandardROIHeadsPseudoLab"
    LOSS: "CrossEntropy" # variant: "CrossEntropy"
    NUM_CLASSES: 20
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (60000, 80000, 90000, 360000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 60000
  IMG_PER_BATCH_LABEL: 8
  IMG_PER_BATCH_UNLABEL: 8
  BASE_LR: 0.04
  CHECKPOINT_PERIOD: 5000
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("cityscapes_fine_instance_seg_train",)
  TRAIN_UNLABEL: ("cityscapes_foggy_val",)
  TEST: ("cityscapes_val","cityscapes_foggy_val")
SEMISUPNET:
  Trainer: "dinoteacher"
  BBOX_THRESHOLD: 0.8
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 20000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "res4"
  DIS_LOSS_WEIGHT: 0.0
  USE_FEATURE_ALIGN: True
  FEATURE_ALIGN_LAYER: "res4"
  ALIGN_MODEL: "dinov3_vitb16" 
  ALIGN_HEAD_TYPE: "MLP"  # attention, MLP, MLP3, linear
  ALIGN_HEAD_PROJ_DIM: 1024
  ALIGN_PROJ_GELU: False
  ALIGN_HEAD_NORMALIZE: True
  ALIGN_EASY_ONLY: True
  FEATURE_ALIGN_TARGET_START: 5000
  FEATURE_ALIGN_LOSS_WEIGHT: 1.0
  FEATURE_ALIGN_LOSS_WEIGHT_TARGET: 1.0 
  LABELER_TARGET_PSEUDOGT: None
  LABELER_PSEUDOGT_SWAP: False
  LABELER_PSEUDOGT_SWAP_ITER: 100000
  DINO_PATCH_SIZE: 14
TEST:
  EVAL_PERIOD: 5000