_BASE_: "./Base-RCNN-C4.yaml"
OUTPUT_DIR: "output/test_vit_labeller"
INPUT:
  CROP:
    ENABLED: True
  MIN_SIZE_TRAIN: (600,)
MODEL:
  PIXEL_STD: [57.375, 57.120, 58.395]
  META_ARCHITECTURE: "DAobjTwoStagePseudoLabGeneralizedRCNN_shortcut"
  BACKBONE:
    NAME: "build_dino_vit_backbone"
  MASK_ON: False
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    IN_FEATURES: ["dino_out"]
    PRE_NMS_TOPK_TRAIN: 12000
    POST_NMS_TOPK_TRAIN: 2000
  ROI_HEADS:
    NAME: "SingleScaleROIHeadsPseudoLab"
    LOSS: "CrossEntropy"
    NUM_CLASSES: 8
    IN_FEATURES: ["dino_out"]
    BATCH_SIZE_PER_IMAGE: 512
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
SOLVER:
  LR_SCHEDULER_NAME: "WarmupTwoStageMultiStepLR"
  STEPS: (60000, 80000, 90000, 360000)
  FACTOR_LIST: (1, 1, 1, 1, 1)
  MAX_ITER: 40000
  IMG_PER_BATCH_LABEL: 8
  IMG_PER_BATCH_UNLABEL: 8
  BASE_LR: 0.01
  CHECKPOINT_PERIOD: 5000
DATALOADER:
  SUP_PERCENT: 100.0
DATASETS:
  CROSS_DATASET: True
  TRAIN_LABEL: ("cityscapes_fine_instance_seg_train",)
  TRAIN_UNLABEL: ("cityscapes_foggy_train",)
  TEST: ("cityscapes_val","cityscapes_foggy_val")
SEMISUPNET:
  DIS_TYPE: "dino_out"
  DIS_LOSS_WEIGHT: 0.0
  Trainer: "dinoteacher"
  BBOX_THRESHOLD: 0.5
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 15000
  EMA_KEEP_RATE: 0.999
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  DINO_PATCH_SIZE: 14
  DINO_BBONE_MODEL: "dinov2_vitg14"
  DINO_BBONE_LR_SCALE: 0.0
  LABELER_TARGET_PSEUDOGT: None
  LABELER_PSEUDOGT_SWAP: False
  LABELER_PSEUDOGT_SWAP_ITER: 100000
TEST:
  EVAL_PERIOD: 5000